version: 2

project_name: homelab-helper

builds:
  - id: homelab-helper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - "-buildvcs=false"
    ldflags:
      - "-X {{ .ModulePath }}/internal/info.Version={{ .Version }}"
    main: ./cmd/homelab-helper

dockers_v2:
  - dockerfile: .goreleaser.Dockerfile
    images:
      - ghcr.io/benfiola/{{ .ProjectName }}
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{.Version}}"

release:
  footer: |
    **Docker Image:** `ghcr.io/benfiola/homelab-helper:{{ .Version }}`

changelog:
  use: github-native
